### ISSUE TITLE
Support for SQK-RNA004?

### ISSUE THREAD

**Issue by rugilemat** [novoalab/m6ABasecaller#1]
Thanks so much for this great tool!

Am I correct to assume it does not support libraries prepped with SQK-RNA004? Are you planning to include this compatability?

**Comment by enovoa** [comment]
Thanks @rugilemat - yes, the current model only supports RNA002. We plan to release a model that will be compatible with RNA004, but this is not done yet. Thanks!

**Comment by rugilemat** [comment]
Great, thanks so much!
