### ISSUE TITLE
Not sure about data to use

### ISSUE THREAD

**Issue by vandoorslaer** [novoalab/m6ABasecaller#2]
Hi,
thanks for creating this software. I have a (stupid) question about it's use.

I ran software using option 2 and basecalled using guppy and your custom rna file. i have a fast5 folder and an output folder
the next step I run modphred using these settings as outlined in your example:
      -f reference.fa 
      -o m6A_basecaller 
       -i path/to/sample1  path/to/sample2  path/to/sample3 

but if I point it to the fast5 folder, how would the software locate the basecalled fastq files from step 1 above?

thank you so much

**Comment by enovoa** [comment]
Hi, sorry for slow response. Did you try running it with pointing to the fast5 folder? thank you

**Comment by soniacruciani** [comment]
Hi @vandoorslaer, 
The input for modphred is anyway fast5 files. What changes is that in option 1 modphred basecalls the raw fast5 files on-the-fly and encondes the modification information in the fastq files, while in option 2 you first generate basecalled fast5 files using guppy and the m6A model, and then modphred encondes the modification information into the fastq files starting from the basecalled fast5 files. 
So even though you have basecalled with guppy, what you need as input is the basecalled fast5, not the fastq. 

You can check if your fast5 file contains modification information with:

`h5ls -r file.fast5 | head`

and you should get read entries with "ModBaseProbs"

Let us know if it worked. 

Cheers!

**Comment by fishpohhx** [comment]
Hi, I was testing out the pipeline and ran into the same confusion. I realised that the newer versions of guppy (I was using 6.5.7, CPU version) don't generate fast5 files, only fastq files. Therefore there was no "basecalled fast5" folder to point modphred to.

To fix it I downloaded an older version of guppy (I used 3.2.4, also CPU version), and re-ran the basecalling command including the "--fast5_out" command. This generated basecalled fast5 files in output_folder/workspace, which you can point modphred to. 

Hope this also fixed your problem!

**Comment by enovoa** [comment]
Thanks @fishpohhx! Yes, indeed it seems that the latest versions of guppy do not generate basecalled fast5 files.
