### ISSUE TITLE
zmq.error.Again: Resource temporarily unavailable

### ISSUE THREAD

**Issue by Yoshi-Ochiai** [novoalab/m6ABasecaller#3]
Hi, 
Thank you for developing the m6Abasecaller model!

I try to run by option 1 with Guppy v3.4.5 and Singularity v3.7.0 but encountered the following error.
How can I solve the error? Thank you.

**command**
```
singularity exec --nv modPhred/modphred-3.6.1_latest.sif modPhred/run \
-c path/to/config/rna_r9.4.1_70bps_m6A_hac.cfg \
--host guppy_basecall_server \
-f path/to/rna_sequence.fa \
-o m6abasecaller \
-i /path/to/fast5_pass/
```

**output and error messages**

> [2023-12-05 16:31:25] ===== Welcome, welcome to modPhred pipeline! =====
> [2023-12-05 16:31:25] Connecting to: guppy_basecall_server:5555 ... [mem:   134 MB]
> [2023-12-05 16:31:25] Encoding modification info from 1 directories... [mem:   134 MB]
> [2023-12-05 16:31:25]  /path/to/fast5_pass/ with 28 Fast5 file(s)... [mem:   134 MB]
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/opt/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "path_to/modPhred/src/guppy_encode_live.py", line 109, in basecalling_worker
>     client.connect()
>   File "/opt/miniconda3/lib/python3.9/site-packages/pyguppyclient/client.py", line 73, in connect
>     config = self._load_config(self.config_name)
>   File "/opt/miniconda3/lib/python3.9/site-packages/pyguppyclient/client.py", line 95, in _load_config
>     loaded_configs = {Config(c).name: Config(c) for c in self.get_configs()}
>   File "/opt/miniconda3/lib/python3.9/site-packages/pyguppyclient/client.py", line 91, in get_configs
>     res = self.send(SimpleRequestType.GET_CONFIGS)
>   File "/opt/miniconda3/lib/python3.9/site-packages/pyguppyclient/client.py", line 55, in send
>     return simple_response(self.recv())
>   File "/opt/miniconda3/lib/python3.9/site-packages/pyguppyclient/client.py", line 65, in recv
>     raise Again()
> zmq.error.Again: Resource temporarily unavailable

**Comment by lpryszcz** [comment]
Hi, could you please try with guppy v3.6.1?

**Comment by Yoshi-Ochiai** [comment]
Hi lpryszcz,
I did run Guppy v3.6.1 again, but the same error message appeared.

**Comment by enovoa** [comment]
hi @Yoshi-Ochiai we are planning to embed modPhred into MasterOfpores NextFlow workflow, to ensure that there are no errors caused by the use of different software versions/dependencies. We hope to have this set up in a couple of weeks and will update the README accordingly. Thanks!

**Comment by Yoshi-Ochiai** [comment]
Hi @enovoa 
OK. I look forward to the update! Thank you!
